### ISSUE TITLE
Fix integration tests

### ISSUE THREAD

**Issue by pgoos** [Sifchain/sifchain-ui#498]
`yarn test --integration=true` is failing.
It covers basic integration test against our testnet and akash.
The test needs to be fixed
```
Error: FAIL src/clients/bridges/IBCBridge/IBCBridge.integration-test.ts
  ● Test suite failed to run

    Cannot find module 'config/chains/akash/akash-testnet' from 'src/clients/bridges/IBCBridge/testFaucets.ts'

    Require stack:
      src/clients/bridges/IBCBridge/testFaucets.ts
      src/clients/bridges/IBCBridge/IBCBridge.integration-test.ts

      1 | import { DirectSecp256k1HdWallet } from "@cosmjs/proto-signing";
      2 | import { SigningStargateClient, coins } from "@cosmjs/stargate";
    > 3 | import { AKASH_TESTNET } from "config/chains/akash/akash-testnet";
        | ^
      4 | import fetch from "cross-fetch";
      5 |
      6 | // This contains TEST tokens only, please be nice and don't take them all.

      at Resolver.resolveModule (../node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (src/clients/bridges/IBCBridge/testFaucets.ts:3:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        7.979 s
Ran all test suites.
```

**Comment by pandaring2you** [comment]
Needed to allow us to update packages and avoid potential security vulnerabilities

**Comment by pandaring2you** [comment]
will sync with @canercandan to look at commands

**Comment by pandaring2you** [comment]
Will sync with @canercandan if he's freed up

**Comment by pandaring2you** [comment]
will continue to investigate, will sync w/Caner if run into roadblocks.

**Comment by pandaring2you** [comment]
getting errors on localnet for minting smart contracts.  to sync wtih @jzvikart on resolving issues

**Comment by pgoos** [comment]
@canercandan would you find some time to discuss localnet use cases for erc20 tokens I pointed out on slack so that we can have a fully functional test environment for UI development?

**Comment by pandaring2you** [comment]
Was not able to sync with Caner, but will pursue a solution with siftool w/ @jzvikart

**Comment by pandaring2you** [comment]
@pgoos to investigate if this is still an issue
