### ISSUE TITLE
Sifchain Dex Home page - Settings button does not react to clicks

### ISSUE THREAD

**Issue by applause-sifchain** [Sifchain/sifchain-ui#823]
View your issue at Applause Testing Services - https://platform.applause.com/products/27939/community-issues/5825744
---- ACTION DETAILS ----

Action Performed:
1. Open https://devnet.sifchain.finance/?_env=testnet
2. Click on the Settings icon on the top right of the page

Expected Result:
Settings icon reacts to clicks and the relevant options window is open.

Actual Result:
Settings icon does not react to clicks.

Additional Info:

Error Code/Message:
 

---- Applause Team Lead Recommendation ----

From Reggie Baraza
 Reproducible: Unsure
 In scope: Yes
 Not a duplicate: yes
 Seems valid: yes
Suggested value: somewhat valuable
Comment: 

---- ENVIRONMENT ----

Language:English,Operating System:macOS,Web Browser:Chrome,Operating System Major Version:Big Sur 11.x,Operating System Version:Big Sur 11.4

---- APPLAUSE PROPERTIES ----

Applause Issue/Bug ID: 5825744

Title: Sifchain Dex Home page - Settings button does not react to clicks
Status: Pending Approval

Type: Functional
Frequency: Every Time
Severity: Low

Product (Build): Sifchain (Web) (Dev.net)
Test Cycle: Sifchain - Cryptocurrency Wallet and Token - Test Case Cycle - 11/17/2022

---- APPLAUSE ATTACHMENT(S) ----

Bug5825744_Screenshot_2022-11-18_at_13.29.48.png : https://platform.applause.com/services/links/v1/external/43f583aff31963c04d789283fd024ae36a0ef089ec2fffb4dc26f7ad23dc0c1a

Bug5825744_Screen_Recording_2022-11-18_at_13.28.48.mp4 : https://platform.applause.com/services/links/v1/external/9586202f29c92bd681529f1e23f112819d3e22514c1f72f747d8ba25995d2605

![Bug5825744_Screenshot_2022-11-18_at_13.29.48.png](https://platform.applause.com/services/links/v1/external/43f583aff31963c04d789283fd024ae36a0ef089ec2fffb4dc26f7ad23dc0c1a)

![Bug5825744_Screen_Recording_2022-11-18_at_13.28.48.mp4](https://platform.applause.com/services/links/v1/external/9586202f29c92bd681529f1e23f112819d3e22514c1f72f747d8ba25995d2605)

**Comment by pgoos** [comment]
It should display the feature toggle settings.
Right now there is some runtime error
```
TypeError: Cannot read properties of null (reading 'object')
    at recallSavedValue (index.9c3e1ef3.js:402:12359)
    at _add (index.9c3e1ef3.js:402:13115)
    at et [as add] (index.9c3e1ef3.js:402:5246)
    at index.9c3e1ef3.js:402:17841
    at Array.forEach (<anonymous>)
    at createGui (index.9c3e1ef3.js:402:17800)
    at Proxy.toggleGui (index.9c3e1ef3.js:402:18362)
```
